version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-packages-v1-{{ .Branch }}-
            - npm-packages-v1-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: npm-packages-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: 'npm run lint'
